image: golang:latest

stages:
    - build
    - test

build:
    stage: build
    artifacts:
        when: on_success
        expire_in: 1 day
        paths:
            - .cache
            - .bin

    before_script:
        - cd $GOPATH/src
        - ln -s $CI_PROJECT_DIR
        - cd $CI_PROJECT_NAME
    script:
        - go get -t ./...
        - go build ./...
    after_script:
        - mkdir -p $CI_PROJECT_DIR/.cache
        - mkdir -p $CI_PROJECT_DIR/.bin
        - cd $GOPATH/src
        - cp -R * $CI_PROJECT_DIR/.cache
        - cd $GOPATH/bin
        - cp -R * $CI_PROJECT_DIR/.bin

unit_test:
    stage: test
    before_script:
        - cd $CI_PROJECT_DIR/.cache
        - cp -R * $GOPATH/src
        - cd $CI_PROJECT_DIR
    dependencies:
        - build
    script:
        - go test ./... -v -coverprofile=coverage.out
        - go tool cover -func=coverage.out