language: python
python:
    - 2.7
    - 3.5

install: 
    - sudo apt-get install libmysqlclient-dev
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install codecov pytest-cov

script:
    - flake8 .
    - pytest -v --cov=propertysuggester

after_success:
    - codecov

notifications:
    email:
        recipients:
            - Ladsgroup@gmail.com
        on_success: change
        on_failure: always
    irc:
        channels:
            - "chat.freenode.net#wikidata-feed"
        on_success: change
        on_failure: always
        template:
            - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
